### ISSUE TITLE
Arm64 work on Termux or Raspberry Pi

### ISSUE THREAD

**Issue by rootmelo92118** [mintme-com/miner#16]
I compiled webchain miner (command line version) base on arm64
If you need work your miner on Android (Termux) or Raspberry Pi.
You can use it.
https://github.com/rootmelo92118/webchain-miner-arm64/releases

https://github.com/rootmelo92118/webchain-miner-arm64

**Comment by cleverrain** [comment]
@rootmelo92118 Hi, thank you for your contribution.
