### ISSUE TITLE
99% CPU load on Linux

### ISSUE THREAD

**Issue by randomsymbols** [mintme-com/miner#17]
**Describe the bug**
99% CPU load on Linux, even though "max-cpu-usage": 75 in "config.json".

**To Reproduce**
1. Download Linux 64 release: "https://github.com/webchain-network/webchain-miner/releases/download/v2.8.0/webchain-miner-2.8.0-linux-amd64.tar.gz".
2. Add your user to "config.json".
3. Run "tmux", then run "./webchain-miner", exit tmux "Ctrl+b d".
4. Run "top" and see CPU usage by "webchain-miner" process.

**Expected behavior**
CPU load not more than set in "config.json" (75% by default).

**Screenshots**
"top" output https://monosnap.com/file/f0RfWCrlX5Fo3IzsPNwbtG2fvi6fdh
"config.json" https://monosnap.com/file/UXESxmuhYPNaAJb95ayiH2jvy6rxWC

**Desktop (please complete the following information):**
 - OS: Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

**Additional context**
webchain-miner release v2.8.0

**Comment by cleverrain** [comment]
Hi @randomsymbols  thank you for reporting it. We will check it.

**Comment by ap-rose** [comment]
I am also experiencing the same issue - CentOS 7 x64

**Comment by danielwebimp** [comment]
@randomsymbols @ap-rose  Hi, please try to set your CPU affinity in config.json file with this http://store.fsxtimes.com/cal-cam.php .
As i know, if you set "threads": 0 this will calculate the optimal number of cores for use based on CPU cache.
You can manually set number of cores for mining by set the number in "threads":
Xmrig can't use percents of core. If you have 1 core it would be 100% always. If you have 4 cores for example you can choose 25%,50%.75% and 100% of CPU. If 2 cores you have only 50% or 100% options.
If you need usage of CPU not at full capacity just don`t use all threads. But set it according to the number of CPU that you have. 
Example : if you have a 2 CPU, you can set these parameters  
"threads": 1 
"max-cpu-usage": 50%

**Comment by danielwebimp** [comment]
And to see the usage, please install "htop" in other to see how behaves your CPU. I tried it and I think the result is satisfying.
