### ISSUE TITLE
Wordpress Plugin

### ISSUE THREAD

**Issue by metallicats** [mintme-com/miner#22]
Maybe you guys can fork this so it can mine MINTME.

Currently, it mines on moneroocean only as the main dev has passed away thus leaving the project without any future.

I know you have a wordpress plugin but this is different as it allowes integration with woocommerce, mycred and gamify point systems.

MINTME seems promising and if anyone can continue with this I believe that WordPress devs would use this again.

**https://github.com/VidYen/VidYen-WordPress-Plugins**

**Comment by danielwebimp** [comment]
> Maybe you guys can fork this so it can mine MINTME.
> 
> Currently, it mines on moneroocean only as the main dev has passed away thus leaving the project without any future.
> 
> I know you have a wordpress plugin but this is different as it allowes integration with woocommerce, mycred and gamify point systems.
> 
> MINTME seems promising and if anyone can continue with this I believe that WordPress devs would use this again.
> 
> **https://github.com/VidYen/VidYen-WordPress-Plugins**

@metallicats  Hi, ok thanks. We will see what we can do.
