### ISSUE TITLE
Apk not working

### ISSUE THREAD

**Issue by Saikatsaha1996** [mintme-com/miner#24]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mintme.com for faster attention.

If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tendo-abc** [comment]
Not described at all
