### ISSUE TITLE
Make error on android phone

### ISSUE THREAD

**Issue by Saikatsaha1996** [mintme-com/miner#25]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mintme.com for faster attention.

If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] MI A2
 - OS: [e.g. iOS8.1] Android 10
![Screenshot_20201123-161456](https://user-images.githubusercontent.com/72664192/99953481-4c6e0880-2da7-11eb-9b38-0d6b98c44622.png)

**Additional context**

**Comment by tendo-abc** [comment]
if you want to mine using your android it would better you use the android [app](https://github.com/mintme-com/miner/releases/download/v2.8.0/webchain-miner-2.8.0-android.apk) or via [coinimp](https://www.coinimp.com/)

**Comment by Saikatsaha1996** [comment]
Thank you
