### ISSUE TITLE
Low HashRate Performance

### ISSUE THREAD

**Issue by LaioX** [mintme-com/miner#26]
Hi, the app works great but i got an AMD Ryzen 5 1600 Six-Core Processor, when i use XMRig i got 2100 H/S

my question is... If this miner is based on xmrig, shouldn't it have a similar performance? Actual: 450 H/S. (google translate)

Thanks !

**Comment by lukaszmatczak** [comment]
Hello
MINTME miner uses different hashing algorithm than XMRig, so hashrate difference is expected and normal.
