### ISSUE TITLE
Miner does not run on android 11

### ISSUE THREAD

**Issue by mrcas** [mintme-com/miner#29]
Tested on android 11. Samsung A32.

xmrig does not run on android 11, arm64-v8a

Here is the error:

fdsan: attempted to close file descriptor 9, expected to be unowned, actually owned by FILE* 0x7a6a019018
Aborted

**Comment by tendo-abc** [comment]
We seem not to find any error on our side, maybe something else is blocking the miner so we advise you to try on a different device
