### ISSUE TITLE
failed to build webchain-miner in armv8 or aarch64

### ISSUE THREAD

**Issue by Zeusyf** [mintme-com/miner#35]
Hello I'm having a problem while building on aarch64 is there a workaround for that?

the following error can be obtained is

[ 97%] Building CXX object CMakeFiles/webchain-miner.dir/src/common/api/HttpRequest.cpp.o
[100%] Linking CXX executable webchain-miner
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libuv.a(libuv_la-fs.o): undefined reference to symbol 'dlsym@@GLIBC_2.17'
/usr/bin/ld: /lib/aarch64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/webchain-miner.dir/build.make:716: webchain-miner] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/webchain-miner.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by ghostmichael499** [comment]
https://github.com/ghostmichael499/MintME.com-aarch64-armv8-miner

**Comment by ghostmichael499** [comment]
> @ghostmichael499 can you mine SRBMiner for Aarch64 or armv8 too?

What do you mean?

**Comment by ghostmichael499** [comment]
> @ghostmichael499 I mean mintme mining tool with Srbminer that compiles on Aarch64 is it possible for you to compile it also to Aarch64?

I don't know if it's possible.. I will try but I don't promise anything!

**Comment by ghostmichael499** [comment]
> @ghostmichael499 let me know if you manage to compile it I will send you 850 USDT as a reward for compiling success

lol 🤣 you crazy dude ... Wish you great day 😘

**Comment by OPGL** [comment]
I succesfully compiled it on aarch64 (oracle linux) using this command:

cmake .. -DUV_LIBRARY=/usr/lib64/libuv.so.1 -DUV_INCLUDE_DIR=/home/opc/webchain-miner/android/libuv/include -DWITH_HTTPD=OFF

(also download all depenencies)
