### ISSUE TITLE
Very necessary ‘proxy mode’ Have plans for this?

### ISSUE THREAD

**Issue by luxig** [mintme-com/miner#4]
Very necessary ‘proxy mode’ Have plans for this?
How to achieve now?

**Comment by lukaszmatczak** [comment]
Do you mean something like xmrig-proxy?

**Comment by luxig** [comment]
> Do you mean something like xmrig-proxy?

YES

**Comment by lsuening** [comment]
Hi devs, is there any updates to support xmrig-proxy?
