### ISSUE TITLE
Trojan Virus in Mintme Miner for wind

### ISSUE THREAD

**Issue by blockchainsuperstar** [mintme-com/miner#41]
*Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mintme.com for faster attention.

If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!*

**Describe the bug**

**To Reproduce**

**Expected behavior**
I am trying to set up the miner on my computer and when I downloaded the version for windows there was a virus which showed up in my scan. A trojan horse at that. I have not opened the files and took pictures. My windows security is what picked up on it. If someone could check this out please let me know because i'd like to mine.
**Screenshots**
I have screen shots on my phone. One from my computer that states it found 2 viruses. One was a trojan horse.
**Desktop (please complete the following information):**
Using Chrome Browser / Github

**Smartphone (please complete the following information):**
 Windows 64

**Additional context**

**Comment by blockchainsuperstar** [comment]
![16610524205496140083338752392550](https://user-images.githubusercontent.com/101999420/185774133-8ff9b074-34f1-4f5c-a839-276d1fcf67a6.jpg)
![16610525916457476559743009587203](https://user-images.githubusercontent.com/101999420/185774146-f8d1f506-165a-4e53-b3c6-5f469930cf8b.jpg)
![16610526147995072403100685957991](https://user-images.githubusercontent.com/101999420/185774150-e34326b4-67f3-44d2-86be-ed3c1393d0f6.jpg)

**Comment by tendo-abc** [comment]
It's known the miners are treated as a virus
