### ISSUE TITLE
Feature bug / request

### ISSUE THREAD

**Issue by phantomkiwi** [mintme-com/miner#5]
Hi

Is it possible in the linux config for you to add / set (define) a port number the webchain-miner local process will work under rather then randomly selecting the next available free port.

This way we can mine on a Nat VPS -port range restricted :) :) :) as we can then specific the free port number we have been allocated to sync to the mining pool.

**Comment by lukaszmatczak** [comment]
Hello
You can setup it at OS level: https://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html#Linux

**Comment by phantomkiwi** [comment]
Hi

Only issue being is NAT hosting providers have that locked (access denied even at root) need someway to change the receiving ip address and socket to the external NAT ip allowed sockets in the actual program / config. Bit like when you set up a VPN script you can tell it the ip and socket you want to listen on.
Sadly it picks up the local ip address too which is internal only, so even if I sort out the socket the external connection wont be able to connect.

Thanks for the info though.
